Name: Recipe
Id: g=58edcee01a14a75e0ff3f1d4f4a0369a
Type: FolderType
Children:
- Name: Val_Bit01ArmPosition
  Type: BaseDataVariableType
  DataType: Int32
  Value: 0
  Children:
  - Name: DynamicLink
    Type: DynamicLink
    DataType: NodePath
    Value: "../../../../CommDrivers/LogixDriver1/LogixStation1/Tags/Program&:Drill/Val_Bit01ArmPosition"
    Children:
    - Name: Mode
      Type: BaseVariableType
      DataType: DynamicLinkMode
      Value: 2
- Name: Val_Bit01Pressure
  Type: BaseDataVariableType
  DataType: Float
  Value: 0.0
  Children:
  - Name: DynamicLink
    Type: DynamicLink
    DataType: NodePath
    Value: "../../../../CommDrivers/LogixDriver1/LogixStation1/Tags/Program&:Drill/Val_Bit01Pressure"
    Children:
    - Name: Mode
      Type: BaseVariableType
      DataType: DynamicLinkMode
      Value: 2
- Name: Val_Bit01RotationSpeed
  Type: BaseDataVariableType
  DataType: Float
  Value: 0.0
  Children:
  - Name: DynamicLink
    Type: DynamicLink
    DataType: NodePath
    Value: "../../../../CommDrivers/LogixDriver1/LogixStation1/Tags/Program&:Drill/Val_Bit01RotationSpeed"
    Children:
    - Name: Mode
      Type: BaseVariableType
      DataType: DynamicLinkMode
      Value: 2
- Name: Val_Bit01Wear
  Type: BaseDataVariableType
  DataType: Float
  Value: 0.0
  Children:
  - Name: DynamicLink
    Type: DynamicLink
    DataType: NodePath
    Value: "../../../../CommDrivers/LogixDriver1/LogixStation1/Tags/Program&:Drill/Val_Bit01Wear"
    Children:
    - Name: Mode
      Type: BaseVariableType
      DataType: DynamicLinkMode
      Value: 2
- Name: Val_Bit02ArmPosition
  Type: BaseDataVariableType
  DataType: Int32
  Value: 0
  Children:
  - Name: DynamicLink
    Type: DynamicLink
    DataType: NodePath
    Value: "../../../../CommDrivers/LogixDriver1/LogixStation1/Tags/Program&:Drill/Val_Bit02ArmPosition"
    Children:
    - Name: Mode
      Type: BaseVariableType
      DataType: DynamicLinkMode
      Value: 2
- Name: Val_Bit02Pressure
  Type: BaseDataVariableType
  DataType: Float
  Value: 0.0
  Children:
  - Name: DynamicLink
    Type: DynamicLink
    DataType: NodePath
    Value: "../../../../CommDrivers/LogixDriver1/LogixStation1/Tags/Program&:Drill/Val_Bit02Pressure"
    Children:
    - Name: Mode
      Type: BaseVariableType
      DataType: DynamicLinkMode
      Value: 2
- Name: Val_Bit02RotationSpeed
  Type: BaseDataVariableType
  DataType: Float
  Value: 0.0
  Children:
  - Name: DynamicLink
    Type: DynamicLink
    DataType: NodePath
    Value: "../../../../CommDrivers/LogixDriver1/LogixStation1/Tags/Program&:Drill/Val_Bit02RotationSpeed"
    Children:
    - Name: Mode
      Type: BaseVariableType
      DataType: DynamicLinkMode
      Value: 2
- Name: Val_Bit02Wear
  Type: BaseDataVariableType
  DataType: Float
  Value: 0.0
  Children:
  - Name: DynamicLink
    Type: DynamicLink
    DataType: NodePath
    Value: "../../../../CommDrivers/LogixDriver1/LogixStation1/Tags/Program&:Drill/Val_Bit02Wear"
    Children:
    - Name: Mode
      Type: BaseVariableType
      DataType: DynamicLinkMode
      Value: 2
- Name: Val_Bit03ArmPosition
  Type: BaseDataVariableType
  DataType: Int32
  Value: 0
  Children:
  - Name: DynamicLink
    Type: DynamicLink
    DataType: NodePath
    Value: "../../../../CommDrivers/LogixDriver1/LogixStation1/Tags/Program&:Drill/Val_Bit03ArmPosition"
    Children:
    - Name: Mode
      Type: BaseVariableType
      DataType: DynamicLinkMode
      Value: 2
- Name: Val_Bit03Pressure
  Type: BaseDataVariableType
  DataType: Float
  Value: 0.0
  Children:
  - Name: DynamicLink
    Type: DynamicLink
    DataType: NodePath
    Value: "../../../../CommDrivers/LogixDriver1/LogixStation1/Tags/Program&:Drill/Val_Bit03Pressure"
    Children:
    - Name: Mode
      Type: BaseVariableType
      DataType: DynamicLinkMode
      Value: 2
- Name: Val_Bit03RotationSpeed
  Type: BaseDataVariableType
  DataType: Float
  Value: 0.0
  Children:
  - Name: DynamicLink
    Type: DynamicLink
    DataType: NodePath
    Value: "../../../../CommDrivers/LogixDriver1/LogixStation1/Tags/Program&:Drill/Val_Bit03RotationSpeed"
    Children:
    - Name: Mode
      Type: BaseVariableType
      DataType: DynamicLinkMode
      Value: 2
- Name: Val_Bit03Wear
  Type: BaseDataVariableType
  DataType: Float
  Value: 0.0
  Children:
  - Name: DynamicLink
    Type: DynamicLink
    DataType: NodePath
    Value: "../../../../CommDrivers/LogixDriver1/LogixStation1/Tags/Program&:Drill/Val_Bit03Wear"
    Children:
    - Name: Mode
      Type: BaseVariableType
      DataType: DynamicLinkMode
      Value: 2
- Name: Val_ForwardSpeed
  Type: BaseDataVariableType
  DataType: Float
  Value: 0.0
  Children:
  - Name: DynamicLink
    Type: DynamicLink
    DataType: NodePath
    Value: "../../../../CommDrivers/LogixDriver1/LogixStation1/Tags/Program&:Drill/Val_ForwardSpeed"
    Children:
    - Name: Mode
      Type: BaseVariableType
      DataType: DynamicLinkMode
      Value: 2
- Name: Val_GuidanceDistance
  Type: BaseDataVariableType
  DataType: Float
  Value: 0.0
  Children:
  - Name: DynamicLink
    Type: DynamicLink
    DataType: NodePath
    Value: "../../../../CommDrivers/LogixDriver1/LogixStation1/Tags/Program&:Drill/Val_GuidanceDistance"
    Children:
    - Name: Mode
      Type: BaseVariableType
      DataType: DynamicLinkMode
      Value: 2
- Name: Val_HeadRotationSpeed
  Type: BaseDataVariableType
  DataType: Float
  Value: 0.0
  Children:
  - Name: DynamicLink
    Type: DynamicLink
    DataType: NodePath
    Value: "../../../../CommDrivers/LogixDriver1/LogixStation1/Tags/Program&:Drill/Val_HeadRotationSpeed"
    Children:
    - Name: Mode
      Type: BaseVariableType
      DataType: DynamicLinkMode
      Value: 2
- Name: Val_LubeHeatersTemperature
  Type: BaseDataVariableType
  DataType: Float
  Value: 0.0
  Children:
  - Name: DynamicLink
    Type: DynamicLink
    DataType: NodePath
    Value: "../../../../CommDrivers/LogixDriver1/LogixStation1/Tags/Program&:Drill/Val_LubeHeatersTemperature"
    Children:
    - Name: Mode
      Type: BaseVariableType
      DataType: DynamicLinkMode
      Value: 2
